# Generated by Django 5.2.3 on 2025-07-08 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsservices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dustreading',
            name='dust_level',
        ),
        migrations.AddField(
            model_name='dustreading',
            name='co',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dustreading',
            name='humidity',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dustreading',
            name='no',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dustreading',
            name='no2',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dustreading',
            name='pm10',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dustreading',
            name='pm25',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dustreading',
            name='so2',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dustreading',
            name='sensor_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dustreading',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dustreading',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
