# Generated by Django 5.2.3 on 2025-07-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsservices', '0002_remove_dustreading_dust_level_dustreading_co_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustreading',
            name='pm25_raw',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
