# Generated by Django 5.2.3 on 2025-07-10 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsservices', '0004_remove_dustreading_pm25_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='dustreading',
            name='raw_payload',
            field=models.TextField(blank=True, null=True),
        ),
    ]
